// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetVigia.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetVigia.Data.Migrations
{
    [DbContext(typeof(UptimeContext))]
    [Migration("20250623184757_ServerPort")]
    partial class ServerPort
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetVigia.Data.Models.ServerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("Active");

                    b.Property<int>("CheckIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("CheckIntervalSeconds");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("ExpectedContent")
                        .HasColumnType("text")
                        .HasColumnName("ExpectedConten");

                    b.Property<int>("ExpectedStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("ExpectedStatusCode");

                    b.Property<Guid?>("IdTGHTTPMethod")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTGHTTPMethod");

                    b.Property<Guid>("IdTGMonitoringType")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTGMonitoringType ");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("Port");

                    b.Property<int>("TimeoutInSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("TimeoutInSeconds");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("URL");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("IdTGHTTPMethod");

                    b.HasIndex("IdTGMonitoringType");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("NetVigia.Data.Models.TabelaGeralItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("Sigla");

                    b.Property<Guid>("TabelaGeralId")
                        .HasColumnType("uuid")
                        .HasColumnName("TabelaGeralId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("TabelaGeralId");

                    b.ToTable("TabelaGeralItem");
                });

            modelBuilder.Entity("NetVigia.Data.Models.TabelaGeralModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.ToTable("TabelaGeral");
                });

            modelBuilder.Entity("NetVigia.Data.Models.ServerModel", b =>
                {
                    b.HasOne("NetVigia.Data.Models.TabelaGeralItemModel", "HTTPMethod")
                        .WithMany()
                        .HasForeignKey("IdTGHTTPMethod");

                    b.HasOne("NetVigia.Data.Models.TabelaGeralItemModel", "MonitoringType")
                        .WithMany()
                        .HasForeignKey("IdTGMonitoringType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HTTPMethod");

                    b.Navigation("MonitoringType");
                });

            modelBuilder.Entity("NetVigia.Data.Models.TabelaGeralItemModel", b =>
                {
                    b.HasOne("NetVigia.Data.Models.TabelaGeralModel", "TabelaGeral")
                        .WithMany()
                        .HasForeignKey("TabelaGeralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabelaGeral");
                });
#pragma warning restore 612, 618
        }
    }
}
