// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetVigia.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetVigia.Data.Migrations
{
    [DbContext(typeof(UptimeContext))]
    [Migration("20250701200845_IntegrationServer")]
    partial class IntegrationServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetVigia.Data.Models.IntegrationServerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId");

                    b.HasIndex("ServerId");

                    b.ToTable("IntegrationServers");
                });

            modelBuilder.Entity("NetVigia.Data.Models.IntegrationUserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("Active");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<Guid>("IdTGIntegrationMethod")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTGIntegrationMethod");

                    b.Property<Guid>("IdTGSendNotification")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTGSendNotification");

                    b.Property<Guid>("IdTGTypeNotification")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTGTypeNotification");

                    b.Property<string>("IntegrationEndpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IntegrationEndpoint");

                    b.Property<string>("IntegrationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IntegrationName");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("IdTGIntegrationMethod");

                    b.HasIndex("IdTGSendNotification");

                    b.HasIndex("IdTGTypeNotification");

                    b.ToTable("Integrations");
                });

            modelBuilder.Entity("NetVigia.Data.Models.MaintenanceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndDate");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.ToTable("Maintenances");
                });

            modelBuilder.Entity("NetVigia.Data.Models.MaintenanceServerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<Guid>("MaintenanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("MaintenanceId");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ServerId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceId");

                    b.HasIndex("ServerId");

                    b.ToTable("MaintenanceServers");
                });

            modelBuilder.Entity("NetVigia.Data.Models.ServerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("Active");

                    b.Property<int>("CheckIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("CheckIntervalSeconds");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("ExpectedContent")
                        .HasColumnType("text")
                        .HasColumnName("ExpectedConten");

                    b.Property<int>("ExpectedStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("ExpectedStatusCode");

                    b.Property<Guid?>("IdTGHTTPMethod")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTGHTTPMethod");

                    b.Property<Guid>("IdTGMonitoringType")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTGMonitoringType ");

                    b.Property<Guid?>("IntegrationUserModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MaintenanceModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("Port");

                    b.Property<int>("TimeoutInSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("TimeoutInSeconds");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("URL");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("IdTGHTTPMethod");

                    b.HasIndex("IdTGMonitoringType");

                    b.HasIndex("IntegrationUserModelId");

                    b.HasIndex("MaintenanceModelId");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("NetVigia.Data.Models.TabelaGeralItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("Sigla");

                    b.Property<Guid>("TabelaGeralId")
                        .HasColumnType("uuid")
                        .HasColumnName("TabelaGeralId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("TabelaGeralId");

                    b.ToTable("TabelaGeralItem");
                });

            modelBuilder.Entity("NetVigia.Data.Models.TabelaGeralModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.ToTable("TabelaGeral");
                });

            modelBuilder.Entity("NetVigia.Data.Models.IntegrationServerModel", b =>
                {
                    b.HasOne("NetVigia.Data.Models.IntegrationUserModel", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetVigia.Data.Models.ServerModel", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integration");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("NetVigia.Data.Models.IntegrationUserModel", b =>
                {
                    b.HasOne("NetVigia.Data.Models.TabelaGeralItemModel", "IntegrationMethod")
                        .WithMany()
                        .HasForeignKey("IdTGIntegrationMethod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetVigia.Data.Models.TabelaGeralItemModel", "SendNotification")
                        .WithMany()
                        .HasForeignKey("IdTGSendNotification")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetVigia.Data.Models.TabelaGeralItemModel", "TypeNotification")
                        .WithMany()
                        .HasForeignKey("IdTGTypeNotification")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationMethod");

                    b.Navigation("SendNotification");

                    b.Navigation("TypeNotification");
                });

            modelBuilder.Entity("NetVigia.Data.Models.MaintenanceServerModel", b =>
                {
                    b.HasOne("NetVigia.Data.Models.MaintenanceModel", "Maintenance")
                        .WithMany()
                        .HasForeignKey("MaintenanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetVigia.Data.Models.ServerModel", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maintenance");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("NetVigia.Data.Models.ServerModel", b =>
                {
                    b.HasOne("NetVigia.Data.Models.TabelaGeralItemModel", "HTTPMethod")
                        .WithMany()
                        .HasForeignKey("IdTGHTTPMethod");

                    b.HasOne("NetVigia.Data.Models.TabelaGeralItemModel", "MonitoringType")
                        .WithMany()
                        .HasForeignKey("IdTGMonitoringType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetVigia.Data.Models.IntegrationUserModel", null)
                        .WithMany("Servers")
                        .HasForeignKey("IntegrationUserModelId");

                    b.HasOne("NetVigia.Data.Models.MaintenanceModel", null)
                        .WithMany("Servers")
                        .HasForeignKey("MaintenanceModelId");

                    b.Navigation("HTTPMethod");

                    b.Navigation("MonitoringType");
                });

            modelBuilder.Entity("NetVigia.Data.Models.TabelaGeralItemModel", b =>
                {
                    b.HasOne("NetVigia.Data.Models.TabelaGeralModel", "TabelaGeral")
                        .WithMany()
                        .HasForeignKey("TabelaGeralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabelaGeral");
                });

            modelBuilder.Entity("NetVigia.Data.Models.IntegrationUserModel", b =>
                {
                    b.Navigation("Servers");
                });

            modelBuilder.Entity("NetVigia.Data.Models.MaintenanceModel", b =>
                {
                    b.Navigation("Servers");
                });
#pragma warning restore 612, 618
        }
    }
}
